name: _scene_dash_v2_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - packages/scene_dash_v2_core
  - packages/scene_dash_v2
  - packages/scene_dash_inspector
  - examples/headless_example
  - examples/scene_game
  - examples/basic_example_tower_defense
  - examples/combat_sample
  - benchmarks

flutter:
  assets:
    - flutter_scene_generated/
